# appveyor file
# http://www.appveyor.com/docs/appveyor-yml

clone_folder: c:\projects\cordova-plugin-alljoyn

install:
  - PowerShell .\tests\InstallCordovaCert.ps1 c:\projects\cordova-plugin-alljoyn\tests\CordovaApp_TemporaryKey.pfx
  - PowerShell Import-module servermanager ; Get-WindowsFeature
  - PowerShell (gwmi win32_computersystem).partofdomain
  - npm install -g grunt-cli
  - npm install
  - cd ..
  - npm install cordova
  - npm install vjrantal/cordova-paramedic

build: off

test_script:
  - cd c:\projects\cordova-plugin-alljoyn
  - grunt test
  - cd ..
  - set PATH=c:\projects\node_modules\.bin;c:\projects\cordova-cli\bin;%PATH%
  - set PLUGIN_PATH=c:/projects/cordova-plugin-alljoyn
  - cordova-paramedic --platform windows --plugin %PLUGIN_PATH% --architecture=x86
