# appveyor file
# http://www.appveyor.com/docs/appveyor-yml

clone_folder: c:\projects\cordova-plugin-alljoyn

environment:
  VARIABLE_1:
    secure: vTDQIfdFkPtRV/EXI6miidRo0BQYCSMCZkpaUNkM01N0WNmw3x0lVLLkLDHewUOCBKHxD/NoBMDbAC3j0NR+h5Dd2ULapUQuClAF2J3ULlXM5KribZTHTPDVNryxJM2q
  VARIABLE_2:
    secure: LnWd0zsvbBYF0TPabaikvnCNUpfOGq2BSoVQL/w+jp4=
  VARIABLE_3:
    secure: UKX+R7zmiDz9FnwmDsya6Q==

install:
  - PowerShell .\tests\InstallCordovaCert.ps1 c:\projects\cordova-plugin-alljoyn\tests\CordovaApp_TemporaryKey.pfx
  - echo %VARIABLE_1%
  - start /B /wait .\tests\DeveloperLicenseAcquirer.exe %VARIABLE_1% %VARIABLE_2% %VARIABLE_3%
  - echo %errorlevel%
  - PowerShell Get-WindowsDeveloperLicense
  - npm install -g grunt-cli
  - npm install
  - cd ..
  - npm install cordova
  - npm install vjrantal/cordova-paramedic

build: off

test_script:
  - cd c:\projects\cordova-plugin-alljoyn
  - grunt test
  - cd ..
  - set PATH=c:\projects\node_modules\.bin;c:\projects\cordova-cli\bin;%PATH%
  - set PLUGIN_PATH=c:/projects/cordova-plugin-alljoyn
  - cordova-paramedic --platform windows --plugin %PLUGIN_PATH% --architecture=x86
